CREATE TABLE IF NOT EXISTS users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR UNIQUE NOT NULL,
    password VARCHAR UNIQUE  NOT NULL
);
CREATE SEQUENCE user_seq;

CREATE TABLE IF NOT EXISTS sessions(
    id UUID PRIMARY KEY,
    user_id INT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX sessions_unique_user_id_idx ON sessions(user_id);
CREATE TABLE IF NOT EXISTS locations(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    user_id INTEGER NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX locations_unique_user_id_latitude_longitude ON locations(user_id,latitude,longitude);
CREATE SEQUENCE location_seq;